import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/features/appwrite/types.ts --verbose`.

export enum ClientsTarget {
    NKC_SCHENGEN = "nkc-schengen",
    NKC_NATIONAL = "nkc-national",
    NDB_SCHENGEN = "ndb-schengen",
    NDB_NATIONAL = "ndb-national"
}

export enum ClientsBookingState {
    PENDING = "pending",
    DONE = "done",
    LOCAL = "local"
}

export enum ClientsGender {
    MALE = "male",
    FEMALE = "female"
}

export type Settings = Models.Row & {
    value: string;
}

export type UsersLogs = Models.Row & {
    message: string;
    subject: string;
}

export type Clients = Models.Row & {
    firstName: string;
    lastName: string;
    passportNumber: string;
    birthdate: string;
    passportIssue: string;
    passportExpire: string;
    passportPhoto: string;
    email: string;
    whale: string;
    status: string;
    day: string;
    photo: string;
    owner: string;
    important: boolean;
    nationality: string;
    birthplace: string;
    target: ClientsTarget;
    visaSubType: string | null;
    bookingState: ClientsBookingState;
    nin: string;
    phoneNumber: string;
    bookedDay: string | null;
    isPremium: boolean;
    gender: ClientsGender;
    isDisabled: boolean;
    createdBy: string | null;
    updatedBy: string | null;
    contactNumbers: string[] | null;
    isReady: boolean;
    applicants: string | null;
    links: string | null;
}

export type EmailsDomains = Models.Row & {
    available: string[] | null;
}

export type Liveness = Models.Row & {
    clientID: string;
    clientName: string;
    clientPhoto: string;
    state: number;
    owner: string;
    userAgent: string;
    proxyPort: string;
    proxyUrl: string;
    code: string;
    cookies: string;
    fingerprint: string;
    detail: string | null;
    url: string;
    paymentUrl: string | null;
}

export type Blackbox = Models.Row & {
    message: string | null;
    client: string | null;
    reason: string | null;
}

export type Notifications = Models.Row & {
    content: string | null;
    target: string;
    isRead: boolean;
    img: string | null;
}
